# Generated by Django 4.0.1 on 2022-01-12 04:49

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0005_alter_author_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='文章编号')),
                ('title', models.CharField(max_length=200, verbose_name='文章标题')),
                ('content', models.TextField(verbose_name='内容')),
                ('pub_time', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('read_count', models.IntegerField(default=0, verbose_name='阅读次数')),
                ('admired_count', models.IntegerField(default=0, verbose_name='点赞次数')),
                ('like_count', models.IntegerField(default=0, verbose_name='喜欢次数')),
                ('collected_count', models.IntegerField(default=0, verbose_name='收藏次数')),
                ('comment_count', models.IntegerField(default=0, verbose_name='评论次数')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='上次修改时间')),
                ('status', models.CharField(choices=[('0', '正常'), ('1', '删除')], max_length=4, verbose_name='上次修改时间')),
                ('article_author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
            options={
                'ordering': ['-pub_time', 'id'],
            },
        ),
    ]
