# Generated by Django 4.0.1 on 2022-01-10 08:38

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='age',
            field=models.IntegerField(default=0, verbose_name='作者年龄'),
        ),
        migrations.AddField(
            model_name='author',
            name='create_time',
            field=models.DateField(default=datetime.datetime.now, verbose_name='注册时间'),
        ),
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, db_index=True, max_length=20, null=True, verbose_name='联系邮箱'),
        ),
        migrations.AddField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', '女'), ('1', '男')], max_length=1, null=True, verbose_name='年龄'),
        ),
        migrations.AddField(
            model_name='author',
            name='intro',
            field=models.TextField(null=True, verbose_name='个人介绍'),
        ),
        migrations.AddField(
            model_name='author',
            name='nickname',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, unique=True, verbose_name='作者昵称'),
        ),
        migrations.AddField(
            model_name='author',
            name='personal_page',
            field=models.URLField(blank=True, null=True, verbose_name='个人主页'),
        ),
        migrations.AddField(
            model_name='author',
            name='phone',
            field=models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='联系电话'),
        ),
        migrations.AddField(
            model_name='author',
            name='remark',
            field=models.TextField(null=True, verbose_name='备注信息'),
        ),
        migrations.AddField(
            model_name='author',
            name='status',
            field=models.CharField(choices=[('0', '正常'), ('1', '锁定'), ('2', '删除')], default='正常', help_text='必须选择其中一个', max_length=5, verbose_name='用户状态'),
        ),
        migrations.AddField(
            model_name='author',
            name='update_time',
            field=models.DateField(auto_now=True, verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('bc403ab0-5ad4-4668-a7c1-3ffa82aecb39'), primary_key=True, serialize=False, verbose_name='作者编号'),
        ),
        migrations.AlterField(
            model_name='author',
            name='realname',
            field=models.CharField(blank=True, db_index=True, default='待完善', max_length=20, null=True, verbose_name='作者姓名'),
        ),
        migrations.AlterField(
            model_name='author',
            name='username',
            field=models.CharField(max_length=50, unique=True, verbose_name='登陆帐号'),
        ),
    ]
