# Generated by Django 4.0.1 on 2022-01-10 08:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_author_age_author_create_time_author_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', '女'), ('1', '男')], max_length=2, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('5f207f0b-eee1-484e-9857-b319955d5b5e'), primary_key=True, serialize=False, verbose_name='作者编号'),
        ),
    ]
