# Generated by Django 4.0.1 on 2022-01-10 08:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0003_alter_author_gender_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='gender',
            field=models.CharField(blank=True, choices=[('0', '女'), ('1', '男')], max_length=1, null=True, verbose_name='年龄'),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('e08a7644-e123-4bbf-88c3-ee29bce5c13f'), primary_key=True, serialize=False, verbose_name='作者编号'),
        ),
    ]
