# Generated by Django 4.0.1 on 2022-01-12 04:49

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0004_alter_author_gender_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('bcd10229-6f20-4bef-b639-123ab3edaafb'), primary_key=True, serialize=False, verbose_name='作者编号'),
        ),
    ]
