# Generated by Django 4.0.1 on 2022-01-12 05:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0005_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('119498d2-321c-4103-af74-8d355b4dbf50'), primary_key=True, serialize=False, verbose_name='作者编号'),
        ),
        migrations.CreateModel(
            name='AuthorProfile',
            fields=[
                ('id', models.UUIDField(auto_created=True, default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='作者编号')),
                ('fans_count', models.IntegerField(default=0, verbose_name='粉丝数量')),
                ('visited_count', models.IntegerField(default=0, verbose_name='访问数量')),
                ('words_count', models.IntegerField(default=0, verbose_name='文章字数')),
                ('article_count', models.IntegerField(default=0, verbose_name='文章篇数')),
                ('collected_count', models.IntegerField(default=0, verbose_name='收藏总数量')),
                ('like_count', models.IntegerField(default=0, verbose_name='喜欢总数量')),
                ('admired_count', models.IntegerField(default=0, verbose_name='点赞总数量')),
                ('profile_author', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='author.author')),
            ],
        ),
    ]
