# Generated by Django 4.0.1 on 2022-01-12 05:26

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
        ('author', '0006_alter_author_id_authorprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='authorprofile',
            name='article_collected',
            field=models.ManyToManyField(related_name='articleCollected', to='article.Article'),
        ),
        migrations.AddField(
            model_name='authorprofile',
            name='article_liked',
            field=models.ManyToManyField(related_name='articleLiked', to='article.Article'),
        ),
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('5237a9fb-57d0-49c1-8ce0-ff2316db6a61'), primary_key=True, serialize=False, verbose_name='作者编号'),
        ),
    ]
