# Generated by Django 4.0.1 on 2022-01-12 05:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0007_authorprofile_article_collected_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('59e6e1ec-ccd1-4d27-8f4b-f07bdb252519'), primary_key=True, serialize=False, verbose_name='作者编号'),
        ),
    ]
