# Generated by Django 4.0.1 on 2022-01-12 05:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0008_alter_author_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='id',
            field=models.UUIDField(auto_created=True, default=uuid.UUID('053f56a8-f3f7-4949-8941-89703d7739b1'), primary_key=True, serialize=False, verbose_name='作者编号'),
        ),
    ]
